---
name: Test Symlink Deep
author: Arne Tarara
description: Symlink test

services:
  test-container:
    type: container
    image: alpine

flow:
  - name: Test symlink Deep
    container: test-container
    commands:
      - type: console
        command: cat /tmp/repo/subfolder/passwd
        log-stdout: true
